### PR TITLE
Spanish translation of getting-started and reactivity pages

### PR DESCRIPTION
**Pull request by chuygil**
Spanish translations for getting-started and reactivity (**revisit)** pages. Created an issue (#49) instead to keep track of task list, since others wanted to help.

I have to look over reactivity page one more time, then this should be good to go.

### CODE REVIEW

**Comment by chuygil** [comment]
@aguilera51284 could you maybe review these two pages for me please?

**Comment by davedbase** [comment]
@jgil-r @aguilera51284 just a quick heads up, we made an adjustment in the English, moved a couple guide in so please make sure you update locally so we don't miss out on them in Spanish :-)

**Comment by aguilera51284** [comment]
sorry for the late reply, i had a vacation trip, i will catch up on everything new :D  hope to be of help

**Comment by davedbase** [comment]
@aguilera51284 @jgil-r hi folks! I hope you're both well. I was wondering if you might have some time to helps us push the Spanish version ahead. I think having it would be really helpful to our community.

Thanks!

**Comment by chuygil** [comment]
Yes. I'll have have `guides`, `api.md`, and `tutorials` section done this weekend. I apologize for not giving updates, I was in the process of moving the past couple weeks!

**Comment by chuygil** [comment]
Is it okay if I close this PR, and start fresh?

**Comment by davedbase** [comment]
@jgil-r that's fine. I'm assuming you're marking the work to date there?

**Comment by chuygil** [comment]
Yes, I am!

**Pull request closed without merging**
