### PR TITLE
Add Russian Translations

### PR DESCRIPTION
**Pull request by ghost**
### Translated:
1. api.md
2. comparison.md
3. faq.md

### CODE REVIEW

**Comment by davedbase** [comment]
Oh also the guides are considered part of the documentation. We don't release them without both included because both sections have language toggles.

**Comment by davedbase** [comment]
@pheianox I'll leave this open for when you get around to guides?

**Comment by ghost** [comment]
No problem. I was busy a bit, yeah, but I'm starting today

**Comment by ghost** [comment]
Done after 7 hours. It was funny tho

**Comment by davedbase** [comment]
@pheianox awesome! Yeah when I did Italian it took me similar amount of time. I wouldn't say it was fun though haha. More like painful :-p. Thank you SO much for this. If you have some spare time we're trying to get just a few pages of the website translated as well: https://github.com/solidjs/solid-site/tree/i18n/lang then we can launch the marketing site + docs launch in Russian =)

**Comment by ghost** [comment]
Happy to help! Team!

Yes, that's so true 👍🏻

Yes, sure, I can find some time

**Pull request merged**
