### PR TITLE
de translations 🇩🇪, wip

### PR DESCRIPTION
**Pull request by atk**
This is work in progress on the german translations, see issue#32

### CODE REVIEW

**Comment by davedbase** [comment]
@atk friendly checkin to see how we're doing here =)

**Comment by atk** [comment]
Back on track, closing in to 50% today, will hopefully continue tomorrow.

**Comment by davedbase** [comment]
Awesome work @atk thanks so much for contributing your time!

**Comment by atk** [comment]
And we're close to 70% of api.md.

**Comment by atk** [comment]
And up to 80% of api.md. Two more evenings of work and then I'll tackle comparison.md and faq.md.

**Comment by ryansolid** [comment]
Honestly so impressed with the effort with these translations. It took me forever to write these docs. I can only imagine the translation efforts.

**Comment by atk** [comment]
api.md is done, comparison.md is done and faq.md is at ~30%.

**Comment by davedbase** [comment]
Looking fantastic @atk :-)

**Pull request merged**
