### PR TITLE
Doc: Portuguese translation 🇧🇷

### PR DESCRIPTION
**Pull request by candidosales**
- [x] `api.md`;
- [x] `comparison.md`;
- [x] `faq.md`;
- [x] `guides/getting-started`;
- [x] `guides/reactivity`;
- [x] `guides/rendering`;
- [x] `guides/server`;

### CODE REVIEW

**Comment by davedbase** [comment]
Obrigada! This is fantastic @candidosales.  =)

**Comment by davedbase** [comment]
@candidosales we noticed that some links are absolute in the docs, can you shorten them to be relative like this: https://github.com/solidjs/solid-docs/pull/15/commits/e5752d50a4ad864cc432ca6b8b9f17e2c22d7173

**Comment by candidosales** [comment]
@davedbase, could you review the PR? If you know someone who knows Portuguese from the community, please invite them to review the PR. :)

**Comment by davedbase** [comment]
@candidosales oh this is amazing! Thanks for much for putting the effort into it. I'm thinking that maybe we should merge it into solid-docs. I'll then reach out the community and ask for opinions and feedback on the translations. How does that sound?

Side note: I just read your blog post about VanHack. I'm from Toronto myself and was so happy to learn about your experience in the city at the DMZ. =) very cool

**Comment by candidosales** [comment]
@davedbase sounds good!! I'm glad you liked the post! Vanhack was a huge step in my career, I'm eternally grateful!

**Comment by davedbase** [comment]
@candidosales forgive my ignorance but would it make sense to change the folder name to `pt` instead of `pt-BR`? Is there that much difference between it and `pt-PT` to separate them?

**Comment by candidosales** [comment]
@davedbase there aren't that many differences, I suppose the folder could be `pt`

**Pull request merged**
