### PR TITLE
Update api.md

### PR DESCRIPTION
**Pull request by igorbabko**

### CODE REVIEW

**Review by edemaine — COMMENTED** [review]
What is the purpose of this change? ~~I don't think a newline can appear in a regular string.~~

**Comment by igorbabko** [comment]
@edemaine it's just a nit improvement to `console.log` output, instead of printing it like this `count =2` it will print it with a space between `=` and a number like this `count = 2`. No real purpose, just a cosmetic thing.

**Comment by edemaine** [comment]
Sorry, I was looking on mobile.  In fact, `console.log("count =", 2)` already prints `count = 2`, so I think this nit is already taken care of. 🙂

**Comment by igorbabko** [comment]
Ah, indeed, thanks for taking a look!

**Pull request closed without merging**
