### PR TITLE
doc: Add Spanish translation 🇪🇸

### LINKED ISSUE #9: Spanish translation 🇪🇸
Hello there! Wanted to ask if you're open to a contribution with a Spanish translation of the docs.

Following with the conversation that you've had with jay-es let me know if you want me to create directly the PR 👍

### PR DESCRIPTION
**Pull request by jnfrati**
A humble and definitely not perfect Spanish translation of the docs! Help is always welcome! 

- guides
  - [ ] getting-started.md
  - [ ]  reactivity.md
  - [ ]  rendering.md
  - [ ]  server.md
- [ ]  api.md
- [ ]  comparison.md
- [ ]  faq.md

### CODE REVIEW

**Comment by davedbase** [comment]
Gracias @jnfrati for tackling this. Spanish will be a big boost for our community. =)

**Comment by davedbase** [comment]
@jnfrati we noticed that some links are absolute in the docs, can you shorten them to be relative like this: https://github.com/solidjs/solid-docs/pull/15/commits/e5752d50a4ad864cc432ca6b8b9f17e2c22d7173

**Comment by jnfrati** [comment]
Hey @davedbase how are you doing? Sure I'll take care of the links. And thank you for letting me contribute!

**Comment by davedbase** [comment]
@jnfrati I'm well thanks for asking. More than happy to receive your contribution!

**Comment by davedbase** [comment]
Just checking in on this, any progress? =)

**Comment by jnfrati** [comment]
Hey @davedbase! I'm so sorry, didn't notice so much time has passed since I opened this, I'll try to finish this on the weekend. Has been a crazy couple of weeks on my work.

**Comment by davedbase** [comment]
@jnfrati no worries. My only concern is someone will see a PR and think that this work is happening. If you decide you can't get through it all I'd prefer to close the PR so that someone feels encouraged to contribute as well. :-) no worries I *totally* understand how tricky it is sometimes to balance work and OSS.

**Comment by jnfrati** [comment]
Absolutely understandable @davedbase, so sorry for not being able to complete this in a shorter period of time. I'll try to work on this and if I manage to finish before another PR is closed I'll create a new one! But I agree this PR should be closed to open the opportunity to other contributors 🤗 

Still thank you for the opportunity and hope to help Solid to grow in any other way!

**Pull request closed without merging**
