### PR TITLE
Clean up the typos, format the code and rephrase some sentences

### PR DESCRIPTION
**Pull request by amoutonbrady**
As mentioned in #20, I ran the French translations through a tool similar to Grammarly (although more powerful and expensive lol), fixed some typos, formatted via prettier and rephrased some sentences / words.

I didn't really read properly the whole thing yet, just mostly corrected the typos.

I'll try to do a second pass later in the week.

(cc @xstevenyung @davedbase)

### CODE REVIEW

**Review by excessivecoding — APPROVED** [review]
LGTM 👌

I need the name of your autocorrector, it seems way better than mine 😁

**Comment by davedbase** [comment]
Hi folks! Just checking in how we're doing here. Looks like French translations have stalled. We might be going live with German and Russian soon, I'd love to see French with it as well. =)

**Comment by amoutonbrady** [comment]
@davedbase I will most likely not have the time to re-read everything but from what I've seen it's in a good enough shape to be published. If anything, this will encourage more people to contribute. Especially people that are used to read technical documentation in French.

I think I fixed most of the typo via my software. Finally putting that 200€ software to use woo.

Thanks again @xstevenyung for all of your work!

PS: The software is called Antidote : https://www.antidote.info/fr

**Comment by davedbase** [comment]
Thanks folks! I'll merge this in for now and we can open new PRs to imprve it.

**Pull request merged**
